encoding    : UTF-8
exclude     : [.idea]
github      : https://github.com/mattwright324/
github_repo : https://github.com/mattwright324/youtube-geofind/
gh_pages    : https://mattw.io/youtube-geofind/